name: Backend CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/route-optimization-service

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run Tests
        run: mvn clean verify

      - name: Print Surefire Report
        if: failure()
        run: find target/surefire-reports -type f cat target/surefire-reports/*.txt